### ISSUE TITLE
Compiled version?

### ISSUE THREAD

**Issue by m2pt5** [Hykem/psxtract#10]
I cannot figure out how to compile this into a usable binary for Windows. I do not have Visual Studio, and MSBUILD says it's missing a file. The free version of VS2010 Express won't open it either.

**Comment by DeadlySystem** [comment]
@Hykem it might be a good idea to add Windows/Unix binaries to the repository and Batch/Bash scripts to simplify usage (Though the Unix people are probably smart enough to compile and use it). Or is there an official build somewhere? I could also host one on my server if desired. I think psxtract could become much more popular if more people were able to use it.

**Comment by killerpommes** [comment]
i wrote a simple GUI for windows in autoit. 
just put the psxtract GUI.exe where the psxtract.exe is and run it.
Maybe it helps for someone. If you find a fault, message me.

https://mega.co.nz/#!P1cAwCrI!kjwjocktqanbV-rbmo_yU6l2mkWAtqnyQeGBUNQf44Q

**Comment by rheimeister** [comment]
the GUI worked! my psextract.exe is still not opening when i clicked it. it
just opens the command prompt and closes immediately...but the gui executed
it and i dnt know how..but thanks ...it worked now

**Comment by Hykem** [comment]
By the way, I'm in the process of adding the reverse functionality (packing and encrypting ISOs).
I've been wanting to add binaries for a long time, but since Github no longer supports hosting them, I'll have to upload them somewhere else. Is SourceForge a good option for this?

**Comment by DeadlySystem** [comment]
I think you can host the binaries on Github, but not as part of the code itself. Instead, you need to make it a "Release". See for example here: https://github.com/elepro/Anthony/releases Not sure how it's done though.

**Comment by Hykem** [comment]
How didn't I ever notice this? Thanks DeadlySystem. :)

**Comment by DeadlySystem** [comment]
You're welcome @Hykem :)

**Comment by Hykem** [comment]
Compiled versions are now available under the "Releases" section.

**Comment by xCELL91** [comment]
what releases section?

**Comment by Hykem** [comment]
https://github.com/Hykem/psxtract/releases

**Comment by killerpommes** [comment]
Maybe you should release another version, because v1.1.1 does not work with multi disk games.
(At least the windows version)
