### ISSUE TITLE
the pre-compiled version in the 'releases' section won't open.

### ISSUE THREAD

**Issue by xCELL91** [Hykem/psxtract#13]
every time i try running it the cmd appears and disappears quickly.

**Comment by Hykem** [comment]
That's normal, it's a console application. You must open CMD.exe first then travel to the directory where you have psxtract (using the "cd" command). Then you can call it and the window won't close anymore.

**Comment by killerpommes** [comment]
Try this in Autoit wrote GUI (For windows)
https://mega.co.nz/#!P1cAwCrI!kjwjocktqanbV-rbmo_yU6l2mkWAtqnyQeGBUNQf44Q

**Comment by xCELL91** [comment]
when i go to the directory and type "start psxtract-v1.1.1-windows-x64" the same thing happens.

**Comment by xCELL91** [comment]
@killerpommes when i drag the eboot in and press ok the cmd opens and starts unpacking, it succeeds. it detects a single disc iso!! found and saved startdat as startdat.bin, OMG... it starts decrypting ISO header... and a 'psxtract.exe has stopped working' , while i'm crying i choose 'check online for solutions' lol right? and then the GUI tells that 'the task should be done' even though it didn't.

**Comment by xCELL91** [comment]
and when i try using the 32-bit version the cmd opens briefly then disappears and the gui informs that the task is done, although i don't notice anything different.
does it extract the isos in the same location of the eboot?

**Comment by killerpommes** [comment]
Just wait a few minutes. 
Windows thinks the programm crashed. but it did not. 
Thats the case if i want to use it,
