### ISSUE TITLE
Using the "-c" option causes a core dump

### ISSUE THREAD

**Issue by CuriousTommy** [Hykem/psxtract#7]
Using this on a Linux machine caused a core dump. I also tested this on a Windows machine and it works perfectly (I was even able to play it on the emulator [PCSX]]!). The game I used was Spyro 2: Ripto's Rage. The program is very awesome! Hopefully you can help me with my issue.

thomasjohnarouge@thomasjohnarouge-G750JW:~/Downloads/psxtract-master/Linux$ ./psxtract -c '/home/thomasjohnarouge/Downloads/EBOOT.PBP' 
Unpacking PBP /home/thomasjohnarouge/Downloads/EBOOT.PBP...
[0]        944 bytes | PARAM.SFO
[1]      13228 bytes | ICON0.PNG
[2]          0 bytes | ICON1.PMF
[3]      34823 bytes | PIC0.PNG
[4]       2651 bytes | PIC1.PNG
[5]          0 bytes | SND0.AT3
[6]      13850 bytes | DATA.PSP
[7]  357938263 bytes | DATA.PSAR
Successfully unpacked /home/thomasjohnarouge/Downloads/EBOOT.PBP!

Single disc ISO detected!

Found STARTDAT offset: 0x15557280
Saving STARTDAT as STARTDAT.BIN...

Decrypting ISO header...
ISO header successfully decrypted! Saving as ISO_HEADER.BIN...

ISO disc: _SCUS_94425
ISO title: Spyro (2): Ripto's Rage!

Found special data offset: 0x1555a117
Decrypting special data...
Special data successfully decrypted! Saving as SPECIAL_DATA.BIN...

Building the final ISO image...
ISO image successfully reconstructed! Saving as ISO.BIN...

Converting the final ISO image...
Fixing CD-ROM image...
The CD-ROM image has been fixed!
Generating CUE file...
ISO image successfully converted to CD-ROM format!
*** Error in `./psxtract': double free or corruption (!prev): 0x0000000001112010 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x80996)[0x7f6509496996]
/lib/x86_64-linux-gnu/libc.so.6(fclose+0x14d)[0x7f65094849bd]
./psxtract[0x400d85]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f6509437de5]
./psxtract[0x400faa]
======= Memory map: ========
00400000-00418000 r-xp 00000000 fc:01 34353396                           /home/thomasjohnarouge/Downloads/psxtract-master/Linux/psxtract
00617000-00618000 r--p 00017000 fc:01 34353396                           /home/thomasjohnarouge/Downloads/psxtract-master/Linux/psxtract
00618000-00619000 rw-p 00018000 fc:01 34353396                           /home/thomasjohnarouge/Downloads/psxtract-master/Linux/psxtract
01112000-037a1000 rw-p 00000000 00:00 0                                  [heap]
7f6509200000-7f6509215000 r-xp 00000000 fc:01 51642412                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f6509215000-7f6509414000 ---p 00015000 fc:01 51642412                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f6509414000-7f6509415000 r--p 00014000 fc:01 51642412                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f6509415000-7f6509416000 rw-p 00015000 fc:01 51642412                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f6509416000-7f65095d3000 r-xp 00000000 fc:01 51646222                   /lib/x86_64-linux-gnu/libc-2.17.so
7f65095d3000-7f65097d3000 ---p 001bd000 fc:01 51646222                   /lib/x86_64-linux-gnu/libc-2.17.so
7f65097d3000-7f65097d7000 r--p 001bd000 fc:01 51646222                   /lib/x86_64-linux-gnu/libc-2.17.so
7f65097d7000-7f65097d9000 rw-p 001c1000 fc:01 51646222                   /lib/x86_64-linux-gnu/libc-2.17.so
7f65097d9000-7f65097de000 rw-p 00000000 00:00 0 
7f65097de000-7f6509801000 r-xp 00000000 fc:01 51646198                   /lib/x86_64-linux-gnu/ld-2.17.so
7f65099d4000-7f65099d7000 rw-p 00000000 00:00 0 
7f65099f9000-7f65099fb000 rw-p 00000000 00:00 0 
7f65099fc000-7f6509a00000 rw-p 00000000 00:00 0 
7f6509a00000-7f6509a01000 r--p 00022000 fc:01 51646198                   /lib/x86_64-linux-gnu/ld-2.17.so
7f6509a01000-7f6509a03000 rw-p 00023000 fc:01 51646198                   /lib/x86_64-linux-gnu/ld-2.17.so
7fff209c8000-7fff209e9000 rw-p 00000000 00:00 0                          [stack]
7fff209fe000-7fff20a00000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)

**Comment by Hykem** [comment]
This issue should now be fixed in v1.1.1.
